### ISSUE TITLE
Angular Universal support

### ISSUE THREAD

**Issue by matbalazsi** [TyrantWave/ng2-parallaxscroll#1]
Is there support for Angular Universal? I am getting this error on the server: 

> ERROR ReferenceError: window is not defined
    at ParallaxScrollDirective.module.exports.ParallaxScrollDirective.ngOnInit

**Comment by TyrantWave** [comment]
Fixed in version 2, should be working fine on local & universal now.

**Comment by TyrantWave** [comment]
https://github.com/TyrantWave/ng2-parallaxscroll/commit/9e62e28112da2e5e8a0f0bb582c6d201f7a48016 v2.0 can handle Universal now.
